= Lau Kar Rui - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: iungo
iungo is a desktop address book application used for learning Software Engineering principles. The user interacts with
it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: Setting of homepage

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=edit]

include::../UserGuide.adoc[tag=add]

#End of Extract#

---

==== Justification

Previous behaviour of both add and edit did not allow the user to set their homepage to something more useful.

This implementation now enhances the usability of the application by allowing the user to set relevant homepages for
each individual contact, such as their Facebook or LinkedIn profiles.

==== Implementation

---
`AddCommand` and `EditCommand` both checks for the `h/` parameter that indicates whether the current homepage is to
be modified.

If `h/` is parsed to be empty by `AddCommandParser` or `EditCommandParser`, a `Person` constructor is used to create
the person with the default homepage.

If `h/` is a non-empty valid URL (determined by `Homepage.isValidHomepage`, a different `Person` constructor is invoked
to create a person with the set homepage.

[NOTE]
Care is also given to make sure the homepage is changed when the name is edited if the current homepage is the default
homepage (i.e. not manually set).

[NOTE]
If the homepage has been set before, it will not change until it is reset by `h/` or a new homepage is manually set.

---

=== Enhancement Added: Sort

==== External behavior
---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=sort]

#End of Extract#

---

==== Justification

Previously, the `list` view of the application would show contacts in the order they were added. For an address book
with many contacts added, sorting would allow the user (who, for some reason, does not want to use the `find` command)
to be able to view the contact list in alphabetical ascending/ descending order.

==== Implementation

---
`SortCommandParser` checks for the OPTIONAL `a` or `d` parameters, and calls the relevant `SortCommand`
to sort the `internalList` backing the address book.

The `internalList` is sorted using the full name of the contact using Java's `sort`.

---

=== Other contributions

{To be included in the future}
